// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.DbContextConfig;

#nullable disable

namespace WebBanHang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260125042912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebBanHang.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Tiểu thuyết"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Khoa học"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Kinh tế"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Thiếu nhi"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Lịch sử"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Tâm lý"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Văn học"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Giáo dục"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            Name = "Ngoại ngữ"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            Name = "Công nghệ"
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Trần Thị B"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lê Văn C"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phạm Thị D"
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hoàng Văn E"
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Đỗ Thị F"
                        },
                        new
                        {
                            Id = 7,
                            CreateAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vũ Văn G"
                        },
                        new
                        {
                            Id = 8,
                            CreateAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bùi Thị H"
                        },
                        new
                        {
                            Id = 9,
                            CreateAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phan Văn I"
                        },
                        new
                        {
                            Id = 10,
                            CreateAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Đặng Thị K"
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 70
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 90
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Quantity = 65
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Quantity = 30
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 1,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 2,
                            Status = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            OrderDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 3,
                            Status = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 4,
                            Status = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            OrderDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            OrderDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 5,
                            Status = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 8,
                            OrderDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 6,
                            Status = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 9,
                            OrderDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 10,
                            OrderDate = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 7,
                            Status = 1,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 50000m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 75000m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 80000m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 90000m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 110000m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 5,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 5,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 70000m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 6,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 130000m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 7,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 160000m
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Name = "Dế Mèn Phiêu Lưu Ký",
                            Price = 50000m,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Nhà Giả Kim",
                            Price = 75000m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Name = "Sapiens",
                            Price = 120000m,
                            SupplierId = 6
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Name = "Cha Giàu Cha Nghèo",
                            Price = 90000m,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Name = "Đắc Nhân Tâm",
                            Price = 80000m,
                            SupplierId = 9
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Harry Potter 1",
                            Price = 110000m,
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 10,
                            Name = "Clean Code",
                            Price = 150000m,
                            SupplierId = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            Name = "English Grammar",
                            Price = 70000m,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            Name = "Tư Duy Nhanh Và Chậm",
                            Price = 130000m,
                            SupplierId = 6
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Name = "Lập Trình C#",
                            Price = 160000m,
                            SupplierId = 7
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SALE10",
                            DiscountPercent = 10m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Code = "SALE15",
                            DiscountPercent = 15m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Code = "SALE20",
                            DiscountPercent = 20m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Code = "BOOK5",
                            DiscountPercent = 5m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Code = "BOOK7",
                            DiscountPercent = 7m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Code = "BOOK12",
                            DiscountPercent = 12m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Code = "VIP20",
                            DiscountPercent = 20m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Code = "VIP25",
                            DiscountPercent = 25m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Code = "TET30",
                            DiscountPercent = 30m,
                            EndDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Code = "SUMMER15",
                            DiscountPercent = 15m,
                            EndDate = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NXB Trẻ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NXB Kim Đồng"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NXB Giáo Dục"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NXB Lao Động"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NXB Văn Học"
                        },
                        new
                        {
                            Id = 6,
                            Name = "NXB Thế Giới"
                        },
                        new
                        {
                            Id = 7,
                            Name = "NXB Khoa Học"
                        },
                        new
                        {
                            Id = 8,
                            Name = "NXB Tổng Hợp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "NXB Phụ Nữ"
                        },
                        new
                        {
                            Id = 10,
                            Name = "NXB Thanh Niên"
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fullname = "Admin System",
                            Password = "123456",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Fullname = "Nhân viên 1",
                            Password = "123456",
                            Role = 1,
                            Username = "staff1"
                        },
                        new
                        {
                            Id = 3,
                            Fullname = "Nhân viên 2",
                            Password = "123456",
                            Role = 1,
                            Username = "staff2"
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            Fullname = "Khách 1",
                            Password = "123456",
                            Role = 2,
                            Username = "cus1"
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 2,
                            Fullname = "Khách 2",
                            Password = "123456",
                            Role = 2,
                            Username = "cus2"
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 3,
                            Fullname = "Khách 3",
                            Password = "123456",
                            Role = 2,
                            Username = "cus3"
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 4,
                            Fullname = "Khách 4",
                            Password = "123456",
                            Role = 2,
                            Username = "cus4"
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 5,
                            Fullname = "Khách 5",
                            Password = "123456",
                            Role = 2,
                            Username = "cus5"
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 6,
                            Fullname = "Khách 6",
                            Password = "123456",
                            Role = 2,
                            Username = "cus6"
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 7,
                            Fullname = "Khách 7",
                            Password = "123456",
                            Role = 2,
                            Username = "cus7"
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Inventory", b =>
                {
                    b.HasOne("WebBanHang.Entity.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("WebBanHang.Entity.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Entity.Order", b =>
                {
                    b.HasOne("WebBanHang.Entity.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Entity.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId");

                    b.HasOne("WebBanHang.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanHang.Entity.OrderItem", b =>
                {
                    b.HasOne("WebBanHang.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Entity.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Entity.Product", b =>
                {
                    b.HasOne("WebBanHang.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Entity.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebBanHang.Entity.User", b =>
                {
                    b.HasOne("WebBanHang.Entity.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebBanHang.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebBanHang.Entity.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanHang.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebBanHang.Entity.Product", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebBanHang.Entity.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
