// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.DbContextConfig;

#nullable disable

namespace WebBanHang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebBanHang.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Tiểu thuyết"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Khoa học"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Kinh tế"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Thiếu nhi"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Lịch sử"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Tâm lý"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Văn học"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Giáo dục"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            Name = "Ngoại ngữ"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            Name = "Công nghệ"
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Quận 1, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nguyenvana@gmail.com",
                            Name = "Nguyễn Văn A",
                            Phone = "0901000001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Quận 3, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tranthib@gmail.com",
                            Name = "Trần Thị B",
                            Phone = "0901000002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Quận 5, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "levanc@gmail.com",
                            Name = "Lê Văn C",
                            Phone = "0901000003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Quận 7, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phamthid@gmail.com",
                            Name = "Phạm Thị D",
                            Phone = "0901000004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Quận Bình Thạnh, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoangvane@gmail.com",
                            Name = "Hoàng Văn E",
                            Phone = "0901000005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Quận Gò Vấp, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dothif@gmail.com",
                            Name = "Đỗ Thị F",
                            Phone = "0901000006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Quận Tân Bình, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vuvang@gmail.com",
                            Name = "Vũ Văn G",
                            Phone = "0901000007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Quận Thủ Đức, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "buithih@gmail.com",
                            Name = "Bùi Thị H",
                            Phone = "0901000008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Quận 12, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phanvani@gmail.com",
                            Name = "Phan Văn I",
                            Phone = "0901000009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Huyện Bình Chánh, TP. Hồ Chí Minh",
                            CreateAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dangthik@gmail.com",
                            Name = "Đặng Thị K",
                            Phone = "0901000010"
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.ImportReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("ImportReceipts");
                });

            modelBuilder.Entity("WebBanHang.Entity.ImportReceiptItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImportReceiptId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ImportReceiptId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportReceiptItems");
                });

            modelBuilder.Entity("WebBanHang.Entity.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 70
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 90
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Quantity = 65
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Quantity = 30
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DiscountAmount = 10000m,
                            FinalPrice = 165000m,
                            OrderDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 1,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DiscountAmount = 20000m,
                            FinalPrice = 260000m,
                            OrderDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 2,
                            Status = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            DiscountAmount = 0m,
                            FinalPrice = 270000m,
                            OrderDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            DiscountAmount = 15000m,
                            FinalPrice = 95000m,
                            OrderDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 3,
                            Status = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            DiscountAmount = 10000m,
                            FinalPrice = 280000m,
                            OrderDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 1,
                            Status = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            DiscountAmount = 0m,
                            FinalPrice = 130000m,
                            OrderDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            DiscountAmount = 20000m,
                            FinalPrice = 140000m,
                            OrderDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromotionId = 2,
                            Status = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 50000m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 75000m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 80000m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 90000m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 110000m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 5,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 5,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 70000m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 6,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 130000m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 7,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 160000m
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Name = "Dế Mèn Phiêu Lưu Ký",
                            Price = 50000m,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Nhà Giả Kim",
                            Price = 75000m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Name = "Sapiens",
                            Price = 120000m,
                            SupplierId = 6
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Name = "Cha Giàu Cha Nghèo",
                            Price = 90000m,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Name = "Đắc Nhân Tâm",
                            Price = 80000m,
                            SupplierId = 9
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Harry Potter 1",
                            Price = 110000m,
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 10,
                            Name = "Clean Code",
                            Price = 150000m,
                            SupplierId = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            Name = "English Grammar",
                            Price = 70000m,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            Name = "Tư Duy Nhanh Và Chậm",
                            Price = 130000m,
                            SupplierId = 6
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Name = "Lập Trình C#",
                            Price = 160000m,
                            SupplierId = 7
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaximumDiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SALE10",
                            Description = "Giảm 10% cho tất cả sản phẩm",
                            DiscountPercentage = 10m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaximumDiscountAmount = 100000m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Code = "SALE20",
                            Description = "Giảm 20% tối đa 200k",
                            DiscountPercentage = 20m,
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaximumDiscountAmount = 200000m,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Code = "NEWUSER",
                            Description = "Ưu đãi cho người dùng mới",
                            DiscountPercentage = 15m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaximumDiscountAmount = 150000m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Code = "BLACKFRIDAY",
                            Description = "Khuyến mãi Black Friday",
                            DiscountPercentage = 30m,
                            EndDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaximumDiscountAmount = 500000m,
                            StartDate = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Code = "EXPIRED",
                            Description = "Mã đã hết hạn để test logic",
                            DiscountPercentage = 5m,
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            MaximumDiscountAmount = 50000m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NXB Trẻ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NXB Kim Đồng"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NXB Giáo Dục"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NXB Lao Động"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NXB Văn Học"
                        },
                        new
                        {
                            Id = 6,
                            Name = "NXB Thế Giới"
                        },
                        new
                        {
                            Id = 7,
                            Name = "NXB Khoa Học"
                        },
                        new
                        {
                            Id = 8,
                            Name = "NXB Tổng Hợp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "NXB Phụ Nữ"
                        },
                        new
                        {
                            Id = 10,
                            Name = "NXB Thanh Niên"
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fullname = "Admin System",
                            Password = "AQAAAAIAAYagAAAAEKiu9yYKdOZ/GZyRUju3MIdxjBxWEZbZB9pa02sjJNzkU+StjeCBsP0tKD3rpgAt3A==",
                            Role = 0,
                            Username = "admin01"
                        },
                        new
                        {
                            Id = 2,
                            Fullname = "Nhân viên 1",
                            Password = "AQAAAAIAAYagAAAAEK510YyGEjGIaxf/vypoaiw9C5rCeLYTq5xn/lcTLI7p/lHi8DUWi9xiHjzty3Zp9g==",
                            Role = 1,
                            Username = "staff01"
                        },
                        new
                        {
                            Id = 3,
                            Fullname = "Nhân viên 2",
                            Password = "AQAAAAIAAYagAAAAEN5GnEIAKvANGi3uT8q/U08rAGwtPa8nSO/f2fAqb99q7wfD909WJN4fKTB+DJ0dgA==",
                            Role = 1,
                            Username = "staff02"
                        });
                });

            modelBuilder.Entity("WebBanHang.Entity.ImportReceipt", b =>
                {
                    b.HasOne("WebBanHang.Entity.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanHang.Entity.ImportReceiptItem", b =>
                {
                    b.HasOne("WebBanHang.Entity.ImportReceipt", "ImportReceipt")
                        .WithMany("ReceiptItems")
                        .HasForeignKey("ImportReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Entity.Inventory", b =>
                {
                    b.HasOne("WebBanHang.Entity.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("WebBanHang.Entity.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Entity.Order", b =>
                {
                    b.HasOne("WebBanHang.Entity.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Entity.Promotion", "Promotion")
                        .WithMany("Orders")
                        .HasForeignKey("PromotionId");

                    b.HasOne("WebBanHang.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanHang.Entity.OrderItem", b =>
                {
                    b.HasOne("WebBanHang.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Entity.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Entity.Product", b =>
                {
                    b.HasOne("WebBanHang.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Entity.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebBanHang.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebBanHang.Entity.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanHang.Entity.ImportReceipt", b =>
                {
                    b.Navigation("ReceiptItems");
                });

            modelBuilder.Entity("WebBanHang.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebBanHang.Entity.Product", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebBanHang.Entity.Promotion", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanHang.Entity.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
